name: Build iPhoneMirroringPatcher

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up system dependencies
      run: |
        brew install cocoapods

    - name: Install dependencies
      run: pod install
      working-directory: ./iPhoneMirroringPatcher

    - name: Build Xcode project
      run: xcodebuild -project ./iPhoneMirroringPatcher/iPhoneMirroringPatcher.xcodeproj -scheme "iPhone Mirroring Patcher" -configuration Release clean build

    - name: Archive build
      run: |
        mkdir -p ${{ github.workspace }}/build
        cp -R ${{ github.workspace }}/iPhoneMirroringPatcher/build/Build/Products/Release/iPhone\ Mirroring\ Patcher ${{ github.workspace }}/build/

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: iPhoneMirroringPatcher
        path: ${{ github.workspace }}/build/*
